### ISSUE TITLE
CMAP's bikeway inventory system

### ISSUE THREAD

**Issue by fgregg** [zorostang/chicago_bike_equity#20] opened 2015-03-06 14:57 UTC
https://datahub.cmap.illinois.gov/dataset/bis

**Comment by easherma** [comment] 2015-03-06 16:15
Yep!

On Fri, Mar 6, 2015 at 8:57 AM, Forest Gregg notifications@github.com
wrote:

> https://datahub.cmap.illinois.gov/dataset/bis
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/zorostang/chicago_bike_equity/issues/20.

## 

Eric Sherman
224-402-0004

This e-mail, and any attachments thereto, is intended only for use by
the addressee(s) named herein and may contain legally privileged
and/or confidential information. If you are not the intended recipient
of this e-mail (or the person responsible for delivering this document
to the intended recipient), you are hereby notified that any
dissemination, distribution, printing or copying of this e-mail, and
any attachment thereto, is strictly prohibited. If you have received
this e-mail in error, please respond to the individual sending the
message, and permanently delete the original and any copy of any
e-mail and printout thereof.

**Comment by stevevance** [comment] 2015-03-09 02:35
It's a duplicate of the City of Chicago's own bike lane GIS file. I don't remember what it offers for the suburbs. 

Side note: It would be cool if CKAN, like Socrata, could provide a map preview of geospatial data.

**Closed as completed by stevevance** 2015-03-09 02:35 UTC
